# Utilities
install mackup # Auto backup settings
install sqlite
install grc
install wget --enable-iri
install coreutils
install spark
install the_silver_searcher # Faster search than ack
install ctags
install imagemagick
install qt # used by Capybara Webkit for headless Javascript integration testing
install watch

# Databases
install redis
install postgres --no-python

# Development
install git
install hub
install rbenv
install ruby-build
install rbenv-gem-rehash
install node
install vim
install tmux

# Open SSL
install openssl
link openssl --force
