update

# Utilities
install mackup # Auto backup settings
install sqlite
install grc
install wget --enable-iri
install coreutils
install spark
install the_silver_searcher # Faster search than ack
install ctags
install imagemagick
install qt # used by Capybara Webkit for headless Javascript integration testing
install watch
install reattach-to-user-namespace # Tmux clipboard
install ack
install tree

tap Goles/battery
install battery

# Databases
install redis
install postgres --no-python

# Development
install git
install hub
install rbenv
install ruby-build
install rbenv-gem-rehash
install node
install vim
install tmux

# Open SSL
install openssl
unlink openssl
link openssl --force

# Readline
install readline
unlink readline
link readline --force

# Casks
cask install github
cask install spotify
cask install skype --appdir=/Applications
cask install google-chrome --appdir=/Applications
cask install slack
cask install vlc --appdir=/Applications
