#!/usr/bin/env bash
#
# bootstrap all things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''
$DOTFILES_ROOT/script/configure_git
$DOTFILES_ROOT/script/symlink
$DOTFILES_ROOT/script/install
echo ''
echo '  All installed!'
